{% set name = "apache-airflow-providers-celery" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_celery-{{ version }}.tar.gz
  sha256: e087d32f8eaada2593248b6c1652465d9c03c4cb8484bfcb8f8f76c5e7207868

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow >=2.8.0
    - celery >=5.3.0,<6,!=5.3.3,!=5.3.2
    - flower >=1.0.0
    - google-re2 >=1.0

test:
  imports:
    - airflow.providers.celery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-celery for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/celery/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-celery/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
