context:
  name: apache-airflow-providers-celery
  version: "3.24.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_celery-${{ version }}.tar.gz
  sha256: 6e522b7356d83ffe401321568c8ecf123797805c927117764f3a2f6908e4ee24

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==4.0.2
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.15.0
    - celery >=5.5.0,<6
    # start celery[redis]
    - redis-py >=4.5.2,<6.5,!=4.5.5,!=5.0.2
    # end celery[redis]
    - flower >=1.0.0

tests:
  - python:
      imports:
        - airflow.providers.celery
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-celery for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-celery/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
